services:
  postgres:
    image: postgres:16-alpine
    container_name: momo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: momo_db
    ports:
      - '5435:5432'
    volumes:
      - momo_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: momo_redis
    ports:
      - '6381:6379'
    volumes:
      - momo_redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  momo_pgdata:
  momo_redisdata:
